import Head from 'next/head'
import Script from 'next/script'
import ProjX from '../components/proj'
import Dashboard from '../components/dashboard'
export default function Home() {
  return (
    <>
      <Head>
        <title>QWB Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
        <Script
          src="https://kit.fontawesome.com/fbadad80a0.js"
          crossOrigin="anonymous"
        ></Script>
      <ProjX />
    </>
  )
}
